### ISSUE TITLE
the illlustrated multiple choice question doesnt work

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-project-template#1]
"@elliec : in testproject2 the illustrated multiple choice question doesnt work, i cant select anything"

**Comment by othieno** [comment]
Fixed in commit 460cf9030830cc221f3f3180084926f0e924b537 by resetting the columns at line [74](https://github.com/spMohanty/geotagx_project_template/commit/460cf9030830cc221f3f3180084926f0e924b537#diff-22e5ec050af92d7cd59afc9d08b88791R74).
