### ISSUE TITLE
Add button to rotate photo

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-project-template#14]
UN-ASIGN photos are often upside down or sideways, Jeremy thought he could add a button to rotate them

**Comment by elliec** [comment]
@supranove hows this coming along?

**Comment by othieno** [comment]
@elliec I finally got it working. You can check out a quick prototype here:
http://rawgit.com/geotagx/geotagx-project-template/master/prototype/image.html

If everything seems to work fine, I can close this and make the changes on the website.

**Comment by elliec** [comment]
@supranove looks good to me, go ahead and make changes on the website
