### ISSUE TITLE
feedback from mozilla on improvements

### ISSUE THREAD

**Issue by elliec** [geotagx/geotagx-project-template#16]
Tried out the Winter Shelter project - comments:

```
Tutorial is good, though would be good to have more than one tutorial image available

Website seems to be grinding to a halt as all three of us at the Edinburgh site are trying to use it at the same time
```

**Comment by spMohanty** [comment]
Linked to the issue : https://github.com/geotagx/geotagx-theme/issues/81

**Comment by othieno** [comment]
@elliec, @spMohanty I'll be closing this issue since:
1. The template allows a project to have more than one tutorial image, someone just needs to add them :)
2. This is more of a server-side issue, linked above.
