### ISSUE TITLE
help missing from within apps

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-project-template#2]
"@elliec : The help is missing from within the application"

**Comment by spMohanty** [comment]
@elliec : Moved this issue to the geotagx_project_template repository, as it discusses an issue from that project. The new issue link can be found at : https://github.com/spMohanty/geotagx_project_template/issues/2

**Comment by othieno** [comment]
This must have been an isolated case when I was testing out a few features on a project. Help should work for all projects now (provided it is available).
