### ISSUE TITLE
Refactor task.csv

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-project-template#5]
`task.csv` needs to be refactored to include just `id`, `source_uri,`image_url`

**Comment by othieno** [comment]
@spMohanty, care to explain `id`? I'm not quite sure where it fits in wrt. the CSV file.

**Comment by spMohanty** [comment]
@supranove : `id` is a unique identifier for each task. It is important if you want to go for an automated way to sync a large and ever changing task list.

Imagine the `tasks.csv` file gets updated everyday, and we have a separated script, ` whose job is to read tasks.csv and add only jobs that are not there on geotagx to the server.

**Comment by othieno** [comment]
I see, but wouldn't a `<source URI, image URL>` pair (maybe even just an `image URL`) be enough to distinguish different tasks?

**Comment by spMohanty** [comment]
@supranove : Yeah it would, but its always a good design decision to have a separate field as the primary key in any data store schema instead of leveraging from some latent uniqueness properties of other fields.
Apart from that, in our case, a separate auto incrementing and integral field called say _id_ , will make each record's "uniqueness" property equally readable for both an automated script, and a human editing the data store say in an excel sheet.

**Comment by othieno** [comment]
@spMohanty Ahh, I see. I thought your reasoning was that the `id` would be to prevent duplication by being something like a checksum (rather than an integer). I get it now :+1:
