### ISSUE TITLE
Style Simple MCQs

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-project-template#6]
The checkboxes in the simple mcq questions need to be styled, so that they go well with the general theme.

**Comment by othieno** [comment]
Hey @spMohanty, does styling the MCQs mean adding a space in between the checkbox and its label (like I did in 9523c7cae8ca5efc1e201e5cccd7834eb112e610) or should I jazz it up a bit by adding a background color the checkbox? Something like this: http://www.csscheckbox.com/checkbox/9392/tiny-black-and-white-fill-checkbox/

**Comment by spMohanty** [comment]
@supranove : Yeah that should work (y) !!
