### ISSUE TITLE
Automated tutorial creation

### ISSUE THREAD

**Issue by spMohanty** [geotagx/geotagx-project-template#9]
@elliec : "Automate the creation of an application's tutorial should be possible as all of the questions and help etc are already there in the application

ideally in the end a volunteer would have the possibility of doing more than one photo as a tutorial and then would be presented with a "test my knowledge" type of question after they have completed a certain number of tasks"

**Comment by elliec** [comment]
Something that would be nice to have in the tutorial, while you are improving it.
On the first question, people should be given a "tour" of the interface. they should be shown where to click to get help (no one ever saw this in the usability testing), That they can zoom, and that they can click on the link to view photo source. In tutorials with illustrated multiple choice we coudl also show them that they can click on the photos to get more info

**Comment by spMohanty** [comment]
@elliec : Thanks for the inputs, and yeah it would be a pretty cool feature, and as a matter of fact, I have done something very similar to this in another project.
@supranove : If you want to give it a try, have a look at `intro.js`[http://usablica.github.io/intro.js/] , its **very** easy to use, and we should very easily have an impressive looking **product tour** for our tutorial using this.

Or you can also consider `hopscotch`[http://linkedin.github.io/hopscotch/#general-usage] , which is pretty sleek too !!

**Comment by othieno** [comment]
@spMohanty Thanks for the tips. I was originally considering [joyride](http://zurb.com/playground/jquery-joyride-feature-tour-plugin) but it might take some time to implement. Intro.js looks really simple to implement and I especially like the fact that it clearly highlights a point of interest by dimming out everything else, while the others don't :) We can always switch to something later on but for now I say we try out intro.js.

**Comment by spMohanty** [comment]
@supranove : Go for it :+1:
